### ISSUE TITLE
getting html autocompletes (such as css) to work

### ISSUE THREAD

**Issue by dvic** [elixir-lsp/vscode-elixir-ls#21]
Did anyone get basic autocomplete of CSS class names and other HTML attributes to work with this plugin? I'm only getting emmet to work by adding
```
  "emmet.includeLanguages": {
    "HTML (EEx)": "html"
  },
```

but autocompletes like
![image](https://user-images.githubusercontent.com/1214337/70481830-170fd280-1ae4-11ea-80fe-a7161437d8d1.png)

are not working (tried both master versions of `bradlc.vscode-tailwindcss` and `ecmel.vscode-html-css`)

**Comment by frankdugan3** [comment]
There's a bug with `bradlc.vscode-tailwindcss` that had a fix merged, but no release yet: https://github.com/bradlc/vscode-tailwindcss/pull/54

**Comment by axelson** [comment]
I believe that would take a significant amount of work. Here is the VSCode documentation on the subject: https://code.visualstudio.com/api/language-extensions/embedded-languages

**Comment by jayjun** [comment]
@dvic For CSS, vscode-tailwindcss autocompletes inside `class`. 0.3.0-alpha.x works with EEx. Download and install alpha releases from [here](https://github.com/bradlc/vscode-tailwindcss/releases).

**Comment by dvic** [comment]
@jayjun nice! I can confirm it now works with 0.3.0-alpha.3 and ElixirLS 0.4.0

**Comment by douglascorrea** [comment]
I'm using ElixirLS v0.5.0 and I'm not able to make emmet to work.


I already put:
```
  "emmet.includeLanguages": {
    "HTML (EEx)": "html",
}
```

But it still don't work. Any ideas?

**Comment by douglascorrea** [comment]
Sorry, I didn't realize there was another PR: https://github.com/elixir-lsp/vscode-elixir-ls/pull/87 which change the configuration.

now you should put:

```
  "emmet.includeLanguages": {
    "html-eex": "html",
  },
```

And this is working :)

**Comment by jayjun** [comment]
The extension has switched to `html-eex`. Do this instead.

```json
"emmet.includeLanguages": {
  "html-eex": "html"
}
```
